### ISSUE TITLE
How to change this project use in Eclipse?

### ISSUE THREAD

**Issue by ysj40540** [joyoyao/superCleanMaster#1]

**Comment by mamatagelanee07** [comment]
You can not change structure of Android studio to Eclipse. I mean by this is We can import Eclipse project in Android studio but not vice versa..

Thank you

**Comment by joyoyao** [comment]
sorry, i am busy ,if i have time, i may to do

**Comment by ysj40540** [comment]
thank you very much, it maybe cost a lot of time,studio is the trend of the future. i will try to change this progect too

**Comment by cuba3** [comment]
> sorry, i am busy ,if i have time, i may to do

Hello, I am also an open source project author. This project has not been maintained for a long time, but we recently encountered a lawsuit where someone used your name to falsely claim to be the author of this project and initiated a false lawsuit with a value of 10 million yuan. Although we won the first instance, there may still be risks in this regard in the second instance and the Supreme Court. If you are willing to assist with this false lawsuit, you can contact me. My vx: guobaidu .is very grateful
